"""Secret redaction for `hermes capture`.

Replaces secret-shaped values with ``${VAR}`` references and records the
discovered variable names for ``secrets.env.example``. Defense in depth:
the user reviews the capture diff before committing, and can extend the
default patterns via ``manifest/.redact.yaml``.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover
    yaml = None

# Value-shape patterns for well-known credential formats.
_DEFAULT_VALUE_PATTERNS: list[str] = [
    r"sk-[A-Za-z0-9_\-]{16,}",            # OpenAI / Anthropic style
    r"sk-ant-[A-Za-z0-9_\-]{16,}",        # Anthropic
    r"ghp_[A-Za-z0-9]{20,}",              # GitHub personal token
    r"gho_[A-Za-z0-9]{20,}",              # GitHub OAuth
    r"github_pat_[A-Za-z0-9_]{20,}",      # GitHub fine-grained PAT
    r"glpat-[A-Za-z0-9_\-]{16,}",         # GitLab PAT
    r"AKIA[0-9A-Z]{16}",                  # AWS access key id
    r"xox[baprs]-[A-Za-z0-9\-]{10,}",     # Slack
    r"AIza[0-9A-Za-z_\-]{30,}",           # Google API key
    r"[0-9]{6,}:[A-Za-z0-9_\-]{30,}",     # Telegram bot token
]

# Field-name fragments that, combined with a high-entropy value, mark a secret.
_SECRET_NAME_RE = re.compile(
    r"(_KEY|_TOKEN|_SECRET|_PASSWORD|_PASSWD|APIKEY|API_KEY|ACCESS_KEY|PRIVATE_KEY)$",
    re.IGNORECASE,
)

_PLACEHOLDER_RE = re.compile(r"^\$\{[A-Za-z_][A-Za-z0-9_]*\}$")
_MIN_ENTROPY_LEN = 16


@dataclass
class Redactor:
    """Stateful redactor that accumulates discovered secret variable names."""

    value_patterns: list[re.Pattern[str]] = field(default_factory=list)
    discovered: dict[str, str] = field(default_factory=dict)  # varname -> placeholder

    @classmethod
    def from_config(cls, redact_yaml: str | Path | None = None) -> "Redactor":
        patterns = [re.compile(p) for p in _DEFAULT_VALUE_PATTERNS]
        if redact_yaml and yaml is not None:
            path = Path(redact_yaml)
            if path.exists():
                cfg = yaml.safe_load(path.read_text()) or {}
                for extra in cfg.get("patterns", []) or []:
                    try:
                        patterns.append(re.compile(extra))
                    except re.error:
                        continue
        return cls(value_patterns=patterns)

    # ---- detection ----

    def _value_is_secret_shaped(self, value: str) -> bool:
        return any(p.search(value) for p in self.value_patterns)

    def looks_like_secret(self, key: str | None, value: Any) -> bool:
        if not isinstance(value, str) or not value:
            return False
        if _PLACEHOLDER_RE.match(value):
            return False  # already a placeholder
        if self._value_is_secret_shaped(value):
            return True
        if key and _SECRET_NAME_RE.search(key) and len(value) >= _MIN_ENTROPY_LEN:
            return True
        return False

    # ---- redaction ----

    @staticmethod
    def _varname_for(key: str | None) -> str:
        if key:
            name = re.sub(r"[^A-Za-z0-9]", "_", key).upper().strip("_")
            if name:
                return name
        return "SECRET"

    def redact_value(self, key: str | None, value: Any) -> tuple[Any, str | None]:
        """Return (possibly-redacted value, varname or None)."""
        if not self.looks_like_secret(key, value):
            return value, None
        varname = self._varname_for(key)
        # Disambiguate collisions where the same var name maps to different keys.
        placeholder = "${%s}" % varname
        self.discovered[varname] = placeholder
        return placeholder, varname

    def redact_mapping(self, mapping: dict[str, Any]) -> dict[str, Any]:
        """Redact every secret-shaped value in a flat mapping (e.g. an env map)."""
        out: dict[str, Any] = {}
        for k, v in mapping.items():
            new_v, _ = self.redact_value(k, v)
            out[k] = new_v
        return out

    def redact_json(self, obj: Any, key: str | None = None) -> Any:
        """Recursively redact secret-shaped values in nested dict/list JSON."""
        if isinstance(obj, dict):
            return {k: self.redact_json(v, key=k) for k, v in obj.items()}
        if isinstance(obj, list):
            return [self.redact_json(v, key=key) for v in obj]
        new_v, _ = self.redact_value(key, obj)
        return new_v

    # ---- output ----

    def secrets_env_example(self) -> str:
        lines = [
            "# Generated by `hermes capture`. Fill in real values and save as",
            "# secrets.env (gitignored). Never commit real secrets.",
            "",
        ]
        for var in sorted(self.discovered):
            lines.append(f"{var}=")
        return "\n".join(lines) + "\n"
